version: '3.0'

services:
  sc-task-backend:
    container_name: sc-task-backend
    build:
      context: ./backend
    ports:
      - '3000:3000'
    depends_on:
      - sc-task-db
    restart: always
    command: yarn start:dev
    environment:
      - APP_PORT=3000
      - DB_HOST=sc-task-db
      - DB_PORT=27017

  sc-task-db:
    container_name: sc-task-db
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://localhost:27017
      MONGO_INITDB_DATABASE: local
    volumes:
      - ./backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/init.js
      - ./backend/mongo/volume:/data/db

  sc-task-frontend:
    container_name: sc-task-frontend
    build:
      context: ./frontend
    command: yarn start
    ports:
      - "3001:3001"
    restart: always
